version: '3.7'
services:
  chromedriver:
    image: redjohnzarra/chromedriver
    tmpfs: /tmp
    environment:
      - DISABLE_X11=false
      - ENABLE_VNC=true
      - EXPOSE_X11=true
    volumes:
      - ./assets:/home/webdriver/assets:ro
    ports:
      - 127.0.0.1:5990:5990
  wdio:
    image: redjohnzarra/wdio
    read_only: true
    tmpfs:
      - /tmp
    environment:
      - WAIT_FOR_HOSTS=chromedriver:4444
    volumes:
      - .:/app:ro
      - ./reports:/app/reports
      - ./allure-report:/app/allure-report
      - ./allure-results:/app/allure-results
    depends_on:
      - chromedriver
