version: '3.7'
services:
  chromedriver:
    image: blueimp/chromedriver
    tmpfs: /tmp
    environment:
      - DISABLE_X11=false
      - ENABLE_VNC=true
      - EXPOSE_X11=true
    volumes:
      - ./assets:/home/webdriver/assets:ro
    ports:
      - 5999
  wdio:
    image: blueimp/wdio
    read_only: true
    tmpfs:
      - /tmp
    volumes:
      - .:/app:ro
      - ./reports:/app/reports
    depends_on:
      - chromedriver
